apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kibana-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: kibana-1606407107-kibana
          servicePort: 5601